"""initial_unified_schema

Revision ID: fd0eb946994b
Revises: 
Create Date: 2026-09-04 22:47:10.151302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd0eb946994b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aml_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('suspect_account_id', sa.String(length=64), nullable=False),
    sa.Column('case_type', sa.String(length=64), nullable=False),
    sa.Column('total_suspicious_volume', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('sar_filed', sa.Boolean(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aml_cases_case_type'), 'aml_cases', ['case_type'], unique=False)
    op.create_index(op.f('ix_aml_cases_suspect_account_id'), 'aml_cases', ['suspect_account_id'], unique=False)
    op.create_table('aml_graph_state',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('graph_name', sa.String(length=128), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('mule_cluster_count', sa.Integer(), nullable=False),
    sa.Column('nodes_json', sa.Text(), nullable=False),
    sa.Column('edges_json', sa.Text(), nullable=False),
    sa.Column('clusters_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=32), nullable=False),
    sa.Column('from_gate', sa.String(length=32), nullable=False),
    sa.Column('to_gate', sa.String(length=32), nullable=False),
    sa.Column('lane_id', sa.String(length=32), nullable=True),
    sa.Column('actual_time_min', sa.Float(), nullable=False),
    sa.Column('min_travel_time_min', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('override_by', sa.String(length=64), nullable=True),
    sa.Column('override_reason', sa.String(length=256), nullable=True),
    sa.Column('override_at', sa.String(length=64), nullable=True),
    sa.Column('detected_at', sa.String(length=64), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomalies_tag_id'), 'anomalies', ['tag_id'], unique=False)
    op.create_index(op.f('ix_anomalies_transaction_id'), 'anomalies', ['transaction_id'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('domain', sa.String(length=32), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('criticality', sa.String(length=32), nullable=False),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_type'), 'assets', ['asset_type'], unique=False)
    op.create_index(op.f('ix_assets_domain'), 'assets', ['domain'], unique=False)
    op.create_table('cameras',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('stream_url', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('fps', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('last_heartbeat', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cyber_threats',
    sa.Column('threat_id', sa.String(length=64), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('asset_id', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('mitigation_action', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('threat_id')
    )
    op.create_index(op.f('ix_cyber_threats_threat_type'), 'cyber_threats', ['threat_type'], unique=False)
    op.create_table('intersections',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('controller_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('signal_phase', sa.String(length=32), nullable=False),
    sa.Column('queue_length', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_permissions_action'), 'permissions', ['action'], unique=False)
    op.create_index(op.f('ix_permissions_resource'), 'permissions', ['resource'], unique=False)
    op.create_table('road_segments',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=False),
    sa.Column('start_node', sa.String(length=64), nullable=False),
    sa.Column('end_node', sa.String(length=64), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('lanes', sa.Integer(), nullable=False),
    sa.Column('speed_limit_kmh', sa.Float(), nullable=False),
    sa.Column('current_speed_kmh', sa.Float(), nullable=False),
    sa.Column('current_volume', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.String(length=32), nullable=False),
    sa.Column('incident_count', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_road_segments_route_id'), 'road_segments', ['route_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=32), nullable=False),
    sa.Column('tollgate_id', sa.String(length=32), nullable=False),
    sa.Column('lane_id', sa.String(length=32), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('route_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_tag_id'), 'scans', ['tag_id'], unique=False)
    op.create_index(op.f('ix_scans_tollgate_id'), 'scans', ['tollgate_id'], unique=False)
    op.create_index(op.f('ix_scans_transaction_id'), 'scans', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_scans_vehicle_plate'), 'scans', ['vehicle_plate'], unique=False)
    op.create_table('security_bans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_value', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('banned_by', sa.String(length=64), nullable=False),
    sa.Column('banned_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_bans_is_active'), 'security_bans', ['is_active'], unique=False)
    op.create_index(op.f('ix_security_bans_target_type'), 'security_bans', ['target_type'], unique=False)
    op.create_index(op.f('ix_security_bans_target_value'), 'security_bans', ['target_value'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_reading', sa.Float(), nullable=False),
    sa.Column('expected_range_min', sa.Float(), nullable=False),
    sa.Column('expected_range_max', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('anomaly_detected', sa.Boolean(), nullable=False),
    sa.Column('last_heartbeat', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('simulation_state',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=128), nullable=True),
    sa.Column('elapsed_seconds', sa.Float(), nullable=False),
    sa.Column('events_emitted', sa.Integer(), nullable=False),
    sa.Column('state_blob', sa.Text(), nullable=False),
    sa.Column('started_at', sa.String(length=64), nullable=True),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tollgate_distances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_gate', sa.String(length=32), nullable=False),
    sa.Column('to_gate', sa.String(length=32), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('min_travel_time_min', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tollgate_distances_from_gate'), 'tollgate_distances', ['from_gate'], unique=False)
    op.create_index(op.f('ix_tollgate_distances_to_gate'), 'tollgate_distances', ['to_gate'], unique=False)
    op.create_table('tollgates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gate_id', sa.String(length=32), nullable=False),
    sa.Column('route', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tollgates_gate_id'), 'tollgates', ['gate_id'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_plate', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_tag_id'), 'vehicles', ['tag_id'], unique=True)
    op.create_index(op.f('ix_vehicles_vehicle_plate'), 'vehicles', ['vehicle_plate'], unique=True)
    op.create_table('incident_timelines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=32), nullable=False),
    sa.Column('permission_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('tracked_vehicles',
    sa.Column('track_id', sa.String(length=64), nullable=False),
    sa.Column('vehicle_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.String(length=64), nullable=False),
    sa.Column('last_seen', sa.String(length=64), nullable=False),
    sa.Column('lane', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('estimated_speed', sa.Float(), nullable=False),
    sa.Column('camera_id', sa.String(length=32), nullable=False),
    sa.Column('license_plate', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id')
    )
    op.create_table('traffic_predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('road_id', sa.String(length=32), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('predicted_volume', sa.Integer(), nullable=False),
    sa.Column('predicted_speed', sa.Float(), nullable=False),
    sa.Column('predicted_congestion', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['road_id'], ['road_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_predictions_road_id'), 'traffic_predictions', ['road_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('token_jti', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_token_jti'), 'user_sessions', ['token_jti'], unique=True)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('fraud_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('transaction_id', sa.String(length=64), nullable=True),
    sa.Column('customer_id', sa.String(length=64), nullable=False),
    sa.Column('fraud_type', sa.String(length=64), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['bank_transactions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fraud_cases_customer_id'), 'fraud_cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fraud_cases_fraud_type'), 'fraud_cases', ['fraud_type'], unique=False)
    op.drop_table('traffic_cameras')
    op.alter_column('alerts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('alerts', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('alerts', 'asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('alerts', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('alerts', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('alerts', 'risk_category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('alerts', 'anomaly_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('alerts', 'scenario',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.drop_index(op.f('idx_alerts_timestamp'), table_name='alerts')
    op.create_index(op.f('ix_alerts_asset'), 'alerts', ['asset'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.add_column('ambulances', sa.Column('hospital_id', sa.String(length=64), nullable=True))
    op.add_column('ambulances', sa.Column('call_sign', sa.String(length=64), nullable=False))
    op.add_column('ambulances', sa.Column('location', sa.String(length=128), nullable=False))
    op.add_column('ambulances', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('ambulances', sa.Column('longitude', sa.Float(), nullable=True))
    op.alter_column('ambulances', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('ambulances', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'AVAILABLE'"))
    op.alter_column('ambulances', 'assigned_patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('ambulances', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_ambulances_hospital_id'), 'ambulances', ['hospital_id'], unique=False)
    op.create_foreign_key(None, 'ambulances', 'patients', ['assigned_patient_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ambulances', 'vehicle_number')
    op.drop_column('ambulances', 'eta_minutes')
    op.drop_column('ambulances', 'destination_hospital')
    op.drop_column('ambulances', 'driver_id')
    op.drop_column('ambulances', 'patient_priority')
    op.drop_column('ambulances', 'current_location')
    op.add_column('audit_logs', sa.Column('actor_id', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_username', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=32), nullable=True))
    op.add_column('audit_logs', sa.Column('resource_type', sa.String(length=64), nullable=False))
    op.add_column('audit_logs', sa.Column('resource_id', sa.String(length=64), nullable=True))
    op.add_column('audit_logs', sa.Column('decision', sa.String(length=32), nullable=False))
    op.add_column('audit_logs', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('audit_logs', sa.Column('user_agent', sa.String(length=256), nullable=True))
    op.add_column('audit_logs', sa.Column('details', sa.Text(), nullable=True))
    op.add_column('audit_logs', sa.Column('created_at', sa.String(length=64), nullable=False))
    op.alter_column('audit_logs', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('audit_logs', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_username'), 'audit_logs', ['actor_username'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.drop_column('audit_logs', 'actor')
    op.drop_column('audit_logs', 'payload')
    op.drop_column('audit_logs', 'target')
    op.add_column('bank_accounts', sa.Column('currency', sa.String(length=8), nullable=False))
    op.add_column('bank_accounts', sa.Column('branch', sa.String(length=64), nullable=False))
    op.add_column('bank_accounts', sa.Column('risk_rating', sa.String(length=32), nullable=False))
    op.alter_column('bank_accounts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('bank_accounts', 'customer_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'SAVINGS'"))
    op.alter_column('bank_accounts', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(50000.0)'))
    op.alter_column('bank_accounts', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('bank_accounts', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_bank_accounts_account_number'), 'bank_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_bank_accounts_customer_id'), 'bank_accounts', ['customer_id'], unique=False)
    op.add_column('bank_transactions', sa.Column('device_id', sa.String(length=64), nullable=True))
    op.add_column('bank_transactions', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('bank_transactions', sa.Column('timestamp', sa.String(length=64), nullable=False))
    op.alter_column('bank_transactions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('bank_transactions', 'account_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'sender_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'receiver_account',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ONLINE_BANKING'"))
    op.alter_column('bank_transactions', 'transaction_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'WIRE_TRANSFER'"))
    op.alter_column('bank_transactions', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(5.0)'))
    op.alter_column('bank_transactions', 'decision',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ALLOWED'"))
    op.alter_column('bank_transactions', 'is_fraud',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('idx_bank_tx_account'), table_name='bank_transactions')
    op.create_index(op.f('ix_bank_transactions_account_id'), 'bank_transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_channel'), 'bank_transactions', ['channel'], unique=False)
    op.create_index(op.f('ix_bank_transactions_receiver_account'), 'bank_transactions', ['receiver_account'], unique=False)
    op.create_index(op.f('ix_bank_transactions_timestamp'), 'bank_transactions', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'bank_transactions', 'bank_accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bank_transactions', 'created_at')
    op.drop_column('bank_transactions', 'is_sar')
    op.drop_column('bank_transactions', 'beneficiary_age_hours')
    op.alter_column('campaigns', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('campaigns', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('campaigns', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('campaigns', 'confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('campaigns', 'first_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('campaigns', 'last_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_campaigns_timestamp'), table_name='campaigns')
    op.alter_column('cross_domain_threats', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('cross_domain_threats', 'threat_actor_ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'device_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('cross_domain_threats', 'first_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'last_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.create_index(op.f('ix_cross_domain_threats_device_id'), 'cross_domain_threats', ['device_id'], unique=False)
    op.create_index(op.f('ix_cross_domain_threats_threat_actor_ip'), 'cross_domain_threats', ['threat_actor_ip'], unique=False)
    op.alter_column('devices', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('devices', 'user_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('devices', 'fingerprint',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('devices', 'os',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('devices', 'browser',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('devices', 'ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=45),
               nullable=False)
    op.alter_column('devices', 'location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('devices', 'trust_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False,
               existing_server_default=sa.text('(100.0)'))
    op.alter_column('devices', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'TRUSTED'"))
    op.alter_column('devices', 'first_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('devices', 'last_seen',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_devices_fingerprint'), 'devices', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'devices', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event_stream', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('event_stream', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('event_stream', 'type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('event_stream', 'source_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('event_stream', 'asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('event_stream', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.drop_index(op.f('idx_events_timestamp'), table_name='event_stream')
    op.create_index(op.f('ix_event_stream_asset'), 'event_stream', ['asset'], unique=False)
    op.create_index(op.f('ix_event_stream_severity'), 'event_stream', ['severity'], unique=False)
    op.create_index(op.f('ix_event_stream_timestamp'), 'event_stream', ['timestamp'], unique=False)
    op.create_index(op.f('ix_event_stream_type'), 'event_stream', ['type'], unique=False)
    op.alter_column('fraud_alerts', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('fraud_alerts', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('fraud_alerts', 'transaction_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('fraud_alerts', 'channel',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('fraud_alerts', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('fraud_alerts', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('fraud_alerts', 'decision',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.drop_index(op.f('idx_fraud_timestamp'), table_name='fraud_alerts')
    op.create_index(op.f('ix_fraud_alerts_timestamp'), 'fraud_alerts', ['timestamp'], unique=False)
    op.create_index(op.f('ix_fraud_alerts_transaction_id'), 'fraud_alerts', ['transaction_id'], unique=False)
    op.add_column('incidents', sa.Column('type', sa.String(length=64), nullable=False))
    op.add_column('incidents', sa.Column('asset_id', sa.String(length=64), nullable=True))
    op.add_column('incidents', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('incidents', sa.Column('domain', sa.String(length=32), nullable=False))
    op.add_column('incidents', sa.Column('risk_score', sa.Float(), nullable=False))
    op.add_column('incidents', sa.Column('detected_at', sa.String(length=64), nullable=False))
    op.add_column('incidents', sa.Column('acknowledged_at', sa.String(length=64), nullable=True))
    op.add_column('incidents', sa.Column('resolved_at', sa.String(length=64), nullable=True))
    op.add_column('incidents', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('incidents', sa.Column('is_escalated', sa.Boolean(), nullable=False))
    op.alter_column('incidents', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('incidents', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('incidents', 'severity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('incidents', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('incidents', 'asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('incidents', 'owner',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('incidents', 'payload',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_incidents_asset_id'), 'incidents', ['asset_id'], unique=False)
    op.create_index(op.f('ix_incidents_detected_at'), 'incidents', ['detected_at'], unique=False)
    op.create_index(op.f('ix_incidents_domain'), 'incidents', ['domain'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_type'), 'incidents', ['type'], unique=False)
    op.drop_column('incidents', 'timestamp')
    op.alter_column('medical_records', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('medical_records', 'patient_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'prescriptions',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'lab_results',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'treatment_notes',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('medical_records', 'sensitivity',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIDENTIAL'"))
    op.alter_column('medical_records', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_medical_patient'), table_name='medical_records')
    op.create_index(op.f('ix_medical_records_doctor_id'), 'medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_records_patient_id'), 'medical_records', ['patient_id'], unique=False)
    op.create_foreign_key(None, 'medical_records', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mitigations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('mitigations', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('mitigations', 'asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('mitigations', 'playbook',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('mitigations', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.create_index(op.f('ix_mitigations_timestamp'), 'mitigations', ['timestamp'], unique=False)
    op.add_column('patients', sa.Column('admission_date', sa.String(length=64), nullable=False))
    op.add_column('patients', sa.Column('vital_signs_json', sa.Text(), nullable=True))
    op.add_column('patients', sa.Column('updated_at', sa.String(length=64), nullable=False))
    op.alter_column('patients', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('patients', 'hospital_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False,
               existing_server_default=sa.text("'H001'"))
    op.alter_column('patients', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               nullable=False)
    op.alter_column('patients', 'department',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('patients', 'assigned_doctor_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('patients', 'assigned_nurse_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('patients', 'room_bed',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('patients', 'condition',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.drop_index(op.f('idx_patients_dept'), table_name='patients')
    op.create_index(op.f('ix_patients_assigned_doctor_id'), 'patients', ['assigned_doctor_id'], unique=False)
    op.create_index(op.f('ix_patients_assigned_nurse_id'), 'patients', ['assigned_nurse_id'], unique=False)
    op.create_index(op.f('ix_patients_department'), 'patients', ['department'], unique=False)
    op.create_index(op.f('ix_patients_hospital_id'), 'patients', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.drop_column('patients', 'vitals')
    op.drop_column('patients', 'created_at')
    op.alter_column('response_actions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('response_actions', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('response_actions', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('response_actions', 'target_asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('response_actions', 'before_risk',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('response_actions', 'after_risk',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('response_actions', 'verification_metrics',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('response_actions', 'actor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('response_actions', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'VERIFIED'"))
    op.drop_index(op.f('idx_response_timestamp'), table_name='response_actions')
    op.create_index(op.f('ix_response_actions_timestamp'), 'response_actions', ['timestamp'], unique=False)
    op.alter_column('risk_history', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('risk_history', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('risk_history', 'asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('risk_history', 'risk_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('risk_history', 'category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.drop_index(op.f('idx_risk_timestamp'), table_name='risk_history')
    op.create_index(op.f('ix_risk_history_asset'), 'risk_history', ['asset'], unique=False)
    op.create_index(op.f('ix_risk_history_timestamp'), 'risk_history', ['timestamp'], unique=False)
    op.alter_column('security_policies', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('security_policies', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=False)
    op.alter_column('security_policies', 'domain',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('security_policies', 'risk_modifier',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('security_policies', 'action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'BLOCK'"))
    op.alter_column('security_policies', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('security_policies', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.create_index(op.f('ix_security_policies_domain'), 'security_policies', ['domain'], unique=False)
    op.create_unique_constraint(None, 'security_policies', ['name'])
    op.alter_column('simulations', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('simulations', 'timestamp',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('simulations', 'scenario_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('simulations', 'target_asset',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('simulations', 'attack_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('simulations', 'intensity',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('simulations', 'duration',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('simulations', 'events_generated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('simulations', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.create_index(op.f('ix_simulations_scenario_id'), 'simulations', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_simulations_timestamp'), 'simulations', ['timestamp'], unique=False)
    op.add_column('traffic_signals', sa.Column('intersection_id', sa.String(length=32), nullable=True))
    op.add_column('traffic_signals', sa.Column('controller_id', sa.String(length=64), nullable=True))
    op.add_column('traffic_signals', sa.Column('cycle_time', sa.Integer(), nullable=True))
    op.add_column('traffic_signals', sa.Column('timing_plan', sa.String(length=64), nullable=False))
    op.add_column('traffic_signals', sa.Column('status', sa.String(length=32), nullable=False))
    op.add_column('traffic_signals', sa.Column('is_compromised', sa.Boolean(), nullable=False))
    op.add_column('traffic_signals', sa.Column('last_command_time', sa.String(length=64), nullable=True))
    op.alter_column('traffic_signals', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               nullable=False)
    op.alter_column('traffic_signals', 'intersection',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=True)
    op.alter_column('traffic_signals', 'zone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('traffic_signals', 'current_state',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'GREEN'"))
    op.alter_column('traffic_signals', 'cycle_time_sec',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(90)'))
    op.alter_column('traffic_signals', 'mode',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'ADAPTIVE'"))
    op.alter_column('traffic_signals', 'is_tampered',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('traffic_signals', 'last_override_by',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('traffic_signals', 'updated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_index(op.f('idx_traffic_signals_zone'), table_name='traffic_signals')
    op.create_index(op.f('ix_traffic_signals_zone'), 'traffic_signals', ['zone'], unique=False)
    op.create_foreign_key(None, 'traffic_signals', 'intersections', ['intersection_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('salt', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('failed_logins', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('risk_score', sa.Float(), nullable=False))
    op.alter_column('users', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('users', 'last_login_at',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'last_login_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'risk_score')
    op.drop_column('users', 'failed_logins')
    op.drop_column('users', 'salt')
    op.drop_column('users', 'email')
    op.drop_constraint(None, 'traffic_signals', type_='foreignkey')
    op.drop_index(op.f('ix_traffic_signals_zone'), table_name='traffic_signals')
    op.create_index(op.f('idx_traffic_signals_zone'), 'traffic_signals', ['zone'], unique=False)
    op.alter_column('traffic_signals', 'updated_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('traffic_signals', 'last_override_by',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('traffic_signals', 'is_tampered',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('traffic_signals', 'mode',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ADAPTIVE'"))
    op.alter_column('traffic_signals', 'cycle_time_sec',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(90)'))
    op.alter_column('traffic_signals', 'current_state',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'GREEN'"))
    op.alter_column('traffic_signals', 'zone',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('traffic_signals', 'intersection',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('traffic_signals', 'id',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('traffic_signals', 'last_command_time')
    op.drop_column('traffic_signals', 'is_compromised')
    op.drop_column('traffic_signals', 'status')
    op.drop_column('traffic_signals', 'timing_plan')
    op.drop_column('traffic_signals', 'cycle_time')
    op.drop_column('traffic_signals', 'controller_id')
    op.drop_column('traffic_signals', 'intersection_id')
    op.drop_index(op.f('ix_simulations_timestamp'), table_name='simulations')
    op.drop_index(op.f('ix_simulations_scenario_id'), table_name='simulations')
    op.alter_column('simulations', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('simulations', 'events_generated',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('simulations', 'duration',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('simulations', 'intensity',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('simulations', 'attack_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('simulations', 'target_asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('simulations', 'scenario_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('simulations', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('simulations', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'security_policies', type_='unique')
    op.drop_index(op.f('ix_security_policies_domain'), table_name='security_policies')
    op.alter_column('security_policies', 'is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('security_policies', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('security_policies', 'action',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'BLOCK'"))
    op.alter_column('security_policies', 'risk_modifier',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('security_policies', 'domain',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('security_policies', 'name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('security_policies', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_risk_history_timestamp'), table_name='risk_history')
    op.drop_index(op.f('ix_risk_history_asset'), table_name='risk_history')
    op.create_index(op.f('idx_risk_timestamp'), 'risk_history', ['timestamp'], unique=False)
    op.alter_column('risk_history', 'category',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('risk_history', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('risk_history', 'asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('risk_history', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('risk_history', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_response_actions_timestamp'), table_name='response_actions')
    op.create_index(op.f('idx_response_timestamp'), 'response_actions', ['timestamp'], unique=False)
    op.alter_column('response_actions', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'VERIFIED'"))
    op.alter_column('response_actions', 'actor',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('response_actions', 'verification_metrics',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('response_actions', 'after_risk',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('response_actions', 'before_risk',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('response_actions', 'target_asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('response_actions', 'action',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_actions', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('response_actions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('patients', sa.Column('created_at', sa.TEXT(), nullable=False))
    op.add_column('patients', sa.Column('vitals', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_hospital_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_department'), table_name='patients')
    op.drop_index(op.f('ix_patients_assigned_nurse_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_assigned_doctor_id'), table_name='patients')
    op.create_index(op.f('idx_patients_dept'), 'patients', ['department'], unique=False)
    op.alter_column('patients', 'condition',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'room_bed',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'assigned_nurse_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'assigned_doctor_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('patients', 'department',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('patients', 'gender',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('patients', 'name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('patients', 'hospital_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'H001'"))
    op.alter_column('patients', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('patients', 'updated_at')
    op.drop_column('patients', 'vital_signs_json')
    op.drop_column('patients', 'admission_date')
    op.drop_index(op.f('ix_mitigations_timestamp'), table_name='mitigations')
    op.alter_column('mitigations', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('mitigations', 'playbook',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('mitigations', 'asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('mitigations', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('mitigations', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.drop_index(op.f('ix_medical_records_patient_id'), table_name='medical_records')
    op.drop_index(op.f('ix_medical_records_doctor_id'), table_name='medical_records')
    op.create_index(op.f('idx_medical_patient'), 'medical_records', ['patient_id'], unique=False)
    op.alter_column('medical_records', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('medical_records', 'sensitivity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'CONFIDENTIAL'"))
    op.alter_column('medical_records', 'treatment_notes',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'lab_results',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'prescriptions',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'diagnosis',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('medical_records', 'doctor_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('medical_records', 'patient_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('medical_records', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('incidents', sa.Column('timestamp', sa.TEXT(), nullable=False))
    op.drop_index(op.f('ix_incidents_type'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_domain'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_detected_at'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_asset_id'), table_name='incidents')
    op.alter_column('incidents', 'payload',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('incidents', 'owner',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incidents', 'asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('incidents', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('incidents', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('incidents', 'title',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('incidents', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('incidents', 'is_escalated')
    op.drop_column('incidents', 'description')
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'acknowledged_at')
    op.drop_column('incidents', 'detected_at')
    op.drop_column('incidents', 'risk_score')
    op.drop_column('incidents', 'domain')
    op.drop_column('incidents', 'location')
    op.drop_column('incidents', 'asset_id')
    op.drop_column('incidents', 'type')
    op.drop_index(op.f('ix_fraud_alerts_transaction_id'), table_name='fraud_alerts')
    op.drop_index(op.f('ix_fraud_alerts_timestamp'), table_name='fraud_alerts')
    op.create_index(op.f('idx_fraud_timestamp'), 'fraud_alerts', ['timestamp'], unique=False)
    op.alter_column('fraud_alerts', 'decision',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fraud_alerts', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('fraud_alerts', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fraud_alerts', 'channel',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fraud_alerts', 'transaction_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('fraud_alerts', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('fraud_alerts', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_event_stream_type'), table_name='event_stream')
    op.drop_index(op.f('ix_event_stream_timestamp'), table_name='event_stream')
    op.drop_index(op.f('ix_event_stream_severity'), table_name='event_stream')
    op.drop_index(op.f('ix_event_stream_asset'), table_name='event_stream')
    op.create_index(op.f('idx_events_timestamp'), 'event_stream', ['timestamp'], unique=False)
    op.alter_column('event_stream', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('event_stream', 'asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('event_stream', 'source_type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('event_stream', 'type',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('event_stream', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('event_stream', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_fingerprint'), table_name='devices')
    op.alter_column('devices', 'last_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'first_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'TRUSTED'"))
    op.alter_column('devices', 'trust_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(100.0)'))
    op.alter_column('devices', 'location',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('devices', 'ip',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('devices', 'browser',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('devices', 'os',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('devices', 'fingerprint',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'user_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('devices', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index(op.f('ix_cross_domain_threats_threat_actor_ip'), table_name='cross_domain_threats')
    op.drop_index(op.f('ix_cross_domain_threats_device_id'), table_name='cross_domain_threats')
    op.alter_column('cross_domain_threats', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('cross_domain_threats', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'last_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'first_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'device_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('cross_domain_threats', 'threat_actor_ip',
               existing_type=sa.String(length=45),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('cross_domain_threats', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('idx_campaigns_timestamp'), 'campaigns', ['last_seen'], unique=False)
    op.alter_column('campaigns', 'last_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('campaigns', 'first_seen',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('campaigns', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('campaigns', 'confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('campaigns', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('campaigns', 'title',
               existing_type=sa.String(length=256),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('campaigns', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.add_column('bank_transactions', sa.Column('beneficiary_age_hours', sa.INTEGER(), server_default=sa.text('(720)'), nullable=True))
    op.add_column('bank_transactions', sa.Column('is_sar', sa.INTEGER(), server_default=sa.text('0'), nullable=True))
    op.add_column('bank_transactions', sa.Column('created_at', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'bank_transactions', type_='foreignkey')
    op.drop_index(op.f('ix_bank_transactions_timestamp'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_receiver_account'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_channel'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_account_id'), table_name='bank_transactions')
    op.create_index(op.f('idx_bank_tx_account'), 'bank_transactions', ['account_id'], unique=False)
    op.alter_column('bank_transactions', 'is_fraud',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('bank_transactions', 'decision',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ALLOWED'"))
    op.alter_column('bank_transactions', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True,
               existing_server_default=sa.text('(5.0)'))
    op.alter_column('bank_transactions', 'transaction_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'WIRE_TRANSFER'"))
    op.alter_column('bank_transactions', 'channel',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ONLINE_BANKING'"))
    op.alter_column('bank_transactions', 'amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'receiver_account',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'sender_name',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'account_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_transactions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('bank_transactions', 'timestamp')
    op.drop_column('bank_transactions', 'ip_address')
    op.drop_column('bank_transactions', 'device_id')
    op.drop_index(op.f('ix_bank_accounts_customer_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_account_number'), table_name='bank_accounts')
    op.alter_column('bank_accounts', 'created_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'ACTIVE'"))
    op.alter_column('bank_accounts', 'balance',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(50000.0)'))
    op.alter_column('bank_accounts', 'account_type',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'SAVINGS'"))
    op.alter_column('bank_accounts', 'account_number',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'customer_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bank_accounts', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('bank_accounts', 'risk_rating')
    op.drop_column('bank_accounts', 'branch')
    op.drop_column('bank_accounts', 'currency')
    op.add_column('audit_logs', sa.Column('target', sa.TEXT(), nullable=True))
    op.add_column('audit_logs', sa.Column('payload', sa.TEXT(), nullable=False))
    op.add_column('audit_logs', sa.Column('actor', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.alter_column('audit_logs', 'action',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('audit_logs', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('audit_logs', 'created_at')
    op.drop_column('audit_logs', 'details')
    op.drop_column('audit_logs', 'user_agent')
    op.drop_column('audit_logs', 'ip_address')
    op.drop_column('audit_logs', 'reason')
    op.drop_column('audit_logs', 'decision')
    op.drop_column('audit_logs', 'resource_id')
    op.drop_column('audit_logs', 'resource_type')
    op.drop_column('audit_logs', 'actor_role')
    op.drop_column('audit_logs', 'actor_username')
    op.drop_column('audit_logs', 'actor_id')
    op.add_column('ambulances', sa.Column('current_location', sa.TEXT(), nullable=False))
    op.add_column('ambulances', sa.Column('patient_priority', sa.TEXT(), server_default=sa.text("'NORMAL'"), nullable=True))
    op.add_column('ambulances', sa.Column('driver_id', sa.TEXT(), nullable=False))
    op.add_column('ambulances', sa.Column('destination_hospital', sa.TEXT(), server_default=sa.text("'City General Hospital (H001)'"), nullable=False))
    op.add_column('ambulances', sa.Column('eta_minutes', sa.INTEGER(), server_default=sa.text('8'), nullable=True))
    op.add_column('ambulances', sa.Column('vehicle_number', sa.TEXT(), nullable=False))
    op.drop_constraint(None, 'ambulances', type_='foreignkey')
    op.drop_index(op.f('ix_ambulances_hospital_id'), table_name='ambulances')
    op.alter_column('ambulances', 'updated_at',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('ambulances', 'assigned_patient_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('ambulances', 'status',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'AVAILABLE'"))
    op.alter_column('ambulances', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('ambulances', 'longitude')
    op.drop_column('ambulances', 'latitude')
    op.drop_column('ambulances', 'location')
    op.drop_column('ambulances', 'call_sign')
    op.drop_column('ambulances', 'hospital_id')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_asset'), table_name='alerts')
    op.create_index(op.f('idx_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.alter_column('alerts', 'scenario',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('alerts', 'anomaly_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('alerts', 'risk_category',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'risk_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'asset',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('alerts', 'timestamp',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('alerts', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=True)
    op.create_table('traffic_cameras',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('location', sa.TEXT(), nullable=False),
    sa.Column('stream_url', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'ONLINE'"), nullable=False),
    sa.Column('fps', sa.REAL(), server_default=sa.text('(30.0)'), nullable=True),
    sa.Column('incident_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('updated_at', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_fraud_cases_fraud_type'), table_name='fraud_cases')
    op.drop_index(op.f('ix_fraud_cases_customer_id'), table_name='fraud_cases')
    op.drop_table('fraud_cases')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_token_jti'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_traffic_predictions_road_id'), table_name='traffic_predictions')
    op.drop_table('traffic_predictions')
    op.drop_table('tracked_vehicles')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index(op.f('ix_vehicles_vehicle_plate'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_tag_id'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_tollgates_gate_id'), table_name='tollgates')
    op.drop_table('tollgates')
    op.drop_index(op.f('ix_tollgate_distances_to_gate'), table_name='tollgate_distances')
    op.drop_index(op.f('ix_tollgate_distances_from_gate'), table_name='tollgate_distances')
    op.drop_table('tollgate_distances')
    op.drop_table('simulation_state')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_security_bans_target_value'), table_name='security_bans')
    op.drop_index(op.f('ix_security_bans_target_type'), table_name='security_bans')
    op.drop_index(op.f('ix_security_bans_is_active'), table_name='security_bans')
    op.drop_table('security_bans')
    op.drop_index(op.f('ix_scans_vehicle_plate'), table_name='scans')
    op.drop_index(op.f('ix_scans_transaction_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_tollgate_id'), table_name='scans')
    op.drop_index(op.f('ix_scans_tag_id'), table_name='scans')
    op.drop_table('scans')
    op.drop_table('roles')
    op.drop_index(op.f('ix_road_segments_route_id'), table_name='road_segments')
    op.drop_table('road_segments')
    op.drop_index(op.f('ix_permissions_resource'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_action'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('intersections')
    op.drop_index(op.f('ix_cyber_threats_threat_type'), table_name='cyber_threats')
    op.drop_table('cyber_threats')
    op.drop_table('cameras')
    op.drop_index(op.f('ix_assets_domain'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_type'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_anomalies_transaction_id'), table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_tag_id'), table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_table('aml_graph_state')
    op.drop_index(op.f('ix_aml_cases_suspect_account_id'), table_name='aml_cases')
    op.drop_index(op.f('ix_aml_cases_case_type'), table_name='aml_cases')
    op.drop_table('aml_cases')
    # ### end Alembic commands ###
